### PR TITLE
Advanced_logic branch

### PR DESCRIPTION
**Pull request by ThomasVermes**
-check box in editor page (template + Englisch)
-SQL request (ReportTweaks.php)
-Button + Bootstrap fn (viewTweaks)

### CODE REVIEW

**Comment by aanunez** [comment]
This looks pretty good. I will accept later today or this week and then make a few changes. Did you already look into pulling report logic created via the builder interface? If its not too hard I'd like to add that for completeness.

**Comment by ThomasVermes** [comment]
that's true, it would be better to integrate also the normal builder interface...but I would have to figure out how to pass these results to the js. (I don't think the workaround I did for the single result of advanced_logic will work for an array, or at least it would not be much elegant).
However, here below you can find the queries for the remaining filter's options.
Tomorrow I will try to match the event_id with the custom_event_label

image
The query for this above should be:
image

```
 $result = $this->query(
        '
select field_name, limiter_group_operator, custom_event_label as limiter_event, limiter_operator, limiter_value 
from redcap_reports_fields
join redcap_events_metadata
on redcap_reports_fields.limiter_event_id = redcap_events_metadata.event_id
where report_id = ? and limiter_group_operator <> ''
      ',
        [
            $report_id,
        ]
    );
```

while for the additional filters:
image
image
```
 $result = $this->query(
        '
                            select custom_event_label as global_limiter_event
                            from redcap_reports_filter_events
                            join redcap_events_metadata
                            on redcap_reports_filter_events.event_id = redcap_events_metadata.event_id
                            where report_id = ?
      ',
        [
            $report_id,
        ]
    );
```

**Comment by aanunez** [comment]
Accepting pull as is, I will be making changes on master today to correct style and wording.

**Comment by ThomasVermes** [comment]
Wonderful =)

**Pull request merged**
